version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: wp_db
    restart: always
    environment:
      MYSQL_DATABASE: wp_db_dev
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: 'random_pass'
      MYSQL_ROOT_PASSWORD: 'random_admin_pass'
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
  #      - ./db-backup.sql:/docker-entrypoint-initdb.d/db_backup.sql

  wordpress:
    image: wordpress:5.5-fpm-alpine
    container_name: wp_app
    restart: always
    depends_on:
      - db
    #      - smtp
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp_db_dev
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: 'random_pass'
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - wp:/var/www/html

  nginx:
    image: nginx:1.18-alpine
    container_name: wp_nginx
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - wp:/var/www/html:ro
    volumes_from:
      - wordpress
    depends_on:
      - wordpress

#  smtp:
#    image: mwader/postfix-relay
#    restart: always
#    environment:
#       POSTFIX_myhostname: your-domain.com
#       OPENDKIM_DOMAINS: your-domain.com
#    volumes:
#      - dkim-data:/etc/opendkim/keys

volumes:
  wp:
  db:
#  dkim-data:
